services:
  portfolio:
    build: .
    container_name: nextjs-portfolio
    restart: always
    ports:
      - "3000:3000"
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
